import { CartDataType, ProductDetailType } from "../dataTypes/interfaces";
export const product: ProductDetailType[] = [
  {
    id: 0,
    productName: "Chocolate0",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 5,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
  {
    id: 1,
    productName: "Chocolate1",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 4,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
  {
    id: 2,
    productName: "Chocolate2",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 5,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
  {
    id: 3,
    productName: "Chocolate3",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 5,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
  {
    id: 4,
    productName: "Chocolate4",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 5,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
  {
    id: 5,
    productName: "Chocolate5",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 5,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
  {
    id: 6,
    productName: "Chocolate6",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 5,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
  {
    id: 7,
    productName: "Chocolate7",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 5,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
  {
    id: 8,
    productName: "Chocolate8",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 5,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
  {
    id: 9,
    productName: "Chocolate9",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 5,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
];

export const cartData: CartDataType[] = [
  {
    id: 0,
    userID: 0,
    productID: 0,
    productName: "product0",
    img: "./fakeData/choco.jpeg",
    quantity: 8,
    price: 3,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 1,
    userID: 1,
    productID: 1,
    productName: "product1",
    img: "./fakeData/choco.jpeg",
    quantity: 5,
    price: 1,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 2,
    userID: 2,
    productID: 2,
    productName: "product2",
    img: "./fakeData/choco.jpeg",
    quantity: 3,
    price: 6,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 3,
    userID: 3,
    productID: 3,
    productName: "product3",
    img: "./fakeData/choco.jpeg",
    quantity: 5,
    price: 4,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 4,
    userID: 4,
    productID: 4,
    productName: "product4",
    img: "./fakeData/choco.jpeg",
    quantity: 2,
    price: 4,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 5,
    userID: 5,
    productID: 5,
    productName: "product5",
    img: "./fakeData/choco.jpeg",
    quantity: 1,
    price: 3,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 6,
    userID: 6,
    productID: 6,
    productName: "product6",
    img: "./fakeData/choco.jpeg",
    quantity: 2,
    price: 7,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 7,
    userID: 7,
    productID: 7,
    productName: "product7",
    img: "./fakeData/choco.jpeg",
    quantity: 4,
    price: 2,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 8,
    userID: 8,
    productID: 8,
    productName: "product8",
    img: "./fakeData/choco.jpeg",
    quantity: 2,
    price: 10,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 9,
    userID: 9,
    productID: 9,
    productName: "product9",
    img: "./fakeData/choco.jpeg",
    quantity: 2,
    price: 1,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 10,
    userID: 10,
    productID: 10,
    productName: "product10",
    img: "./fakeData/choco.jpeg",
    quantity: 4,
    price: 9,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 11,
    userID: 11,
    productID: 11,
    productName: "product11",
    img: "./fakeData/choco.jpeg",
    quantity: 9,
    price: 8,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 12,
    userID: 12,
    productID: 12,
    productName: "product12",
    img: "./fakeData/choco.jpeg",
    quantity: 2,
    price: 10,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 13,
    userID: 13,
    productID: 13,
    productName: "product13",
    img: "./fakeData/choco.jpeg",
    quantity: 7,
    price: 4,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 14,
    userID: 14,
    productID: 14,
    productName: "product14",
    img: "./fakeData/choco.jpeg",
    quantity: 10,
    price: 8,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 15,
    userID: 15,
    productID: 15,
    productName: "product15",
    img: "./fakeData/choco.jpeg",
    quantity: 7,
    price: 8,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 16,
    userID: 16,
    productID: 16,
    productName: "product16",
    img: "./fakeData/choco.jpeg",
    quantity: 10,
    price: 10,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 17,
    userID: 17,
    productID: 17,
    productName: "product17",
    img: "./fakeData/choco.jpeg",
    quantity: 8,
    price: 2,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 18,
    userID: 18,
    productID: 18,
    productName: "product18",
    img: "./fakeData/choco.jpeg",
    quantity: 5,
    price: 1,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
  {
    id: 19,
    userID: 19,
    productID: 19,
    productName: "product19",
    img: "./fakeData/choco.jpeg",
    quantity: 7,
    price: 4,
    category: "chocolate",
    createdAt: "2025-11-29T05:46:54.183Z",
  },
];

//  const cartData = () => {
//     const newArr: CartDataType[] = [];

//     for (let i = 0; i < 20; i++) {
//       const obj: CartDataType = {
//         id: i,
//         userID: i,
//         productID: i,
//         productName: `product${i}`,
//         img: "./fakeData/choco.jpeg",
//         quantity: Math.floor(Math.random() * 10) + 1,
//         price: Math.floor(Math.random() * 10) + 1,
//         category: "chocolate",
//         createdAt: new Date(),
//       };

//       newArr.push(obj);
//     }

//     console.log(newArr);
//   };
//   useLayoutEffect(() => {
//     cartData();
//   }, []);
