import { ProductDetailType } from "../dataTypes/interfaces";
export const product: ProductDetailType[] = [
  {
    id: 0,
    productName: "Chocolate0",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 5,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
  {
    id: 1,
    productName: "Chocolate1",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 4,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
  {
    id: 2,
    productName: "Chocolate2",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 5,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
  {
    id: 3,
    productName: "Chocolate3",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 5,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
  {
    id: 4,
    productName: "Chocolate4",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 5,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
  {
    id: 5,
    productName: "Chocolate5",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 5,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
  {
    id: 6,
    productName: "Chocolate6",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 5,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
  {
    id: 7,
    productName: "Chocolate7",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 5,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
  {
    id: 8,
    productName: "Chocolate8",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 5,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
  {
    id: 9,
    productName: "Chocolate9",
    category: "chocolate",
    price: 23,
    inventoryStatus: 5,
    rating: 5,
    createdAt: 3234,
    img: "./fakeData/choco.jpeg",
  },
];
